language: ruby

rvm: 1.9.2

before_script:
  - "psql -c 'create database cmu_education_test;' -U postgres >/dev/null"
  - cp config/amazon_s3.default.yml config/amazon_s3.yml
  - cp config/database.default.yml config/database.yml
  - cp config/morning_glory.default.yml config/morning_glory.yml
  - cp config/systems.default.yml config/systems.yml
  - bundle exec rake db:schema:load RAILS_ENV='test' --trace
  - echo "hello"
  - mkdir tmpdir

script:
  - bundle exec rspec spec_no_rails/
  - bundle exec rake --verbose --trace
#  - bundle exec rake jasmine:ci

env:
  - LDAP_HOST="127.0.0.1" LDAP_PORT=3897 LDAP_USERNAME=anyone LDAP_PASSWORD=anysecret LDAP_ENCRYPTED=false SEARCHIFY_API_URL=foo SEARCHIFY_INDEX=cmux_test SEARCHIFY_STAFF_INDEX=cmu_staffx_test WHITEBOARD_SALT=I_am_salt_with_no_iodine TMPDIR=tmpdir WHITEBOARD_GOOGLE_USERNAME=fall.2010.mfse@sandbox.sv.cmu.edu WHITEBOARD_GOOGLE_PASSWORD=replaceKCzqxP WHITEBOARD_GOOGLE_DOMAIN=sandbox.sv.cmu.edu WHITEBOARD_S3_BUCKET=some_random_placeholder WHITEBOARD_S3_KEY=so_that_travis_will_work WHITEBOARD_S3_SECRET=cmusv-travis WHITEBOARD_TWIKI_USERNAME=none WHITEBOARD_TWIKI_PASSWORD=whatever WHITEBOARD_TWIKI_URL=http://info.sv.cmu.edu



notifications:
  email:
    recipients:
      - todd.sedano@sv.cmu.edu
      - rofaida.abdelaal@sv.cmu.edu
    # on_success: [always|never|change] # default: change
    # on_failure: [always|never|change] # default: always
    on_success: change
    on_failure: always
